[package]
name = "mmvec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap2 = "0.9.4"

[dev-dependencies]
uuid = { version = "1.6.1", features = ["v4"] }
